# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b460365608ece468304002e6765fe1df10e7396bf48889ec99a40c0d3ce24c8d0d113605055190de225bd5279e3d1900cb426708eb67c21dcd0107a423398d20

test:
  secret_key_base: f13f28602842565346e9213c421ffef5d85a056b24bbfd013d4024048d8fd0200cfa848f5309335ae3b8d78dce5e44c547336ff2ceb290ffe000746d81302c8c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
